# Generated by Django 3.2.7 on 2021-09-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_exclusivecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='website',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='exclusivecontent',
            name='website',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='website',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='website',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
